local M = {}

-- Theme for statusline
M.colors = {
    bg = "#1F1F23",
    black = "#1B1B1B",
    skyblue = "#50B0F0",
    cyan = "#009090",
    fg = "#D0D0D0",
    green = "#60A040",
    oceanblue = "#0066cc",
    connected = "#b8bb26",
    magenta = "#C26BDB",
    orange = "#FF9000",
    red = "#ea6962",
    violet = "#9E93E8",
    white = "#FFFFFF",
    yellow = "#E1E120",
    warning = "#fabd2f",
    hint = "#83a598",
    info = "#a0c980",
    error = "#ea6962"
}

M.separators = {
    dos = " ",
    unix = " ",
    mac = " ",
    square = "❖",
    pencil = "",
    circle = "●",
    locker = "",
    confirm = "✓",
    page = "☰",
    git = "",
    line_number = "",
    connected = "",
    spell = "Ⓢ",
    math_l = "𝑳",
    plus = "+",
    minus = "-",
    tilde = "~",
    vertical_bar = "|",
    vertical_bar_thick = "┃",
    vertical_bar_thin = "│",
    left = "",
    right = "",
    block = "█",
    left_filled = "",
    right_filled = "",
    slant_left = "",
    slant_left_thin = "",
    slant_right = "",
    slant_right_thin = "",
    slant_left_2 = "",
    slant_left_2_thin = "",
    slant_right_2 = "",
    slant_right_2_thin = "",
    left_rounded = "",
    left_rounded_thin = "",
    right_rounded = "",
    right_rounded_thin = ""
}

return M
